### ISSUE TITLE
使用异步servlet的时候，会报错

### ISSUE THREAD

**Issue by limx198918** [alipay/sofa-tracer#62]
<dependency>
				<groupId>com.alipay.sofa</groupId>
				<artifactId>tracer-sofa-boot-starter</artifactId>
				<version>2.1.1</version>
			</dependency>

			<dependency>
				<groupId>io.zipkin.java</groupId>
				<artifactId>zipkin</artifactId>
				<version>1.19.2</version>
			</dependency>

			<dependency>
				<groupId>io.zipkin.reporter</groupId>
				<artifactId>zipkin-reporter</artifactId>
				<version>0.6.12</version>
			</dependency>
上面使用依赖包，使用异步servlet的时候，会报错：
java.lang.IllegalStateException: getOutputStream() has already been called for this response。
能紧急更新吗？我们已经发布线上，目前紧急回退了

**Comment by ujjboy** [comment]
@limx198918   好的，堆栈也发下吧。

**Comment by guanchao-yang** [comment]
@limx198918 你好，你的使用方式也发下吧。

**Comment by limx198918** [comment]
下面是错误信息：
Exception in thread "pool-1-thread-7" java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:625)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
	at com.sto.customerapp.courierSentList.servlet.CourierSentListProcess.writerSuccess(CourierSentListProcess.java:52)
	at com.sto.customerapp.courierSentList.servlet.CourierSentListProcess.run(CourierSentListProcess.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
八月 31, 2018 10:38:16 上午 org.apache.catalina.core.AsyncContextImpl timeout
警告: onTimeout() failed for listener of type [org.apache.catalina.core.AsyncListenerWrapper]
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:625)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
	at com.sto.customerapp.courierSentList.servlet.CourierSentListServlet$1.onTimeout(CourierSentListServlet.java:104)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:134)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:153)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:225)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

八月 31, 2018 10:38:32 上午 zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1 onError
警告: Dropped 1 spans due to ResourceAccessException(I/O error on POST request for "http://172.16.200.155:9411/api/v1/spans": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect)
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://172.16.200.155:9411/api/v1/spans": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590)
	at com.alipay.sofa.tracer.boot.zipkin.sender.ZipkinRestTemplateSender.post(ZipkinRestTemplateSender.java:110)
	at com.alipay.sofa.tracer.boot.zipkin.sender.ZipkinRestTemplateSender.sendSpans(ZipkinRestTemplateSender.java:77)
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228)
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153)
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	... 8 more

八月 31, 2018 10:38:54 上午 zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1 onError
警告: Dropped 1 spans due to ResourceAccessException(I/O error on POST request for "http://172.16.200.155:9411/api/v1/spans": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect)
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://172.16.200.155:9411/api/v1/spans": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590)
	at com.alipay.sofa.tracer.boot.zipkin.sender.ZipkinRestTemplateSender.post(ZipkinRestTemplateSender.java:110)
	at com.alipay.sofa.tracer.boot.zipkin.sender.ZipkinRestTemplateSender.sendSpans(ZipkinRestTemplateSender.java:77)
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228)
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153)
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	... 8 more

**Comment by limx198918** [comment]
使用方式：
protected void writerSuccess(CourierSentListRes result) {
		ServletResponse response = asyncContext.getResponse();
		PrintWriter out = null;
		try {
			out = response.getWriter();
		} catch (IOException e) {
			logger.error("【快递发送列表输出流IO异常】:", e);
		}

		out.write(gson.toJson(result));
		out.flush();
		out.close();
	}

===================================================
writerSuccess(courierSentListRes);
				asyncContext.complete();
				return;

**Comment by QilongZhang** [comment]
@limx198918  能否提供下联系方式，拉个微信/钉钉群，我们单独支持。

**Comment by guanchao-yang** [comment]
@limx198918 你再我们微信群里面吗？单独加下我们微信 蚂蚁-雪连 看下你的使用问题。

**Comment by limx198918** [comment]
我在4群里面,名字是：宝贝妞，没有看到蚂蚁-雪连这个人，我的微信号:13662625320

**Comment by guanchao-yang** [comment]
@limx198918 好的

**Comment by guanchao-yang** [comment]
@limx198918 我再里面的，我无法添加你。你设置了隐私，麻烦加下。

**Comment by guanchao-yang** [comment]
@limx198918 其中的堆栈反映出两个问题：

* 问题 1 ： 即异步 Servlet 的问题，我们在[这里](https://github.com/alipay/sofa-tracer/pull/63) 修复

* 问题2： 即 

```
警告: Dropped 1 spans due to ResourceAccessException(I/O error on POST request for "http://172.16.200.155:9411/api/v1/spans": Connection timed out: connect; nested exception is 
```

是由于你没有部署 Zipkin 服务端，但是却引入了 Zipkin 的客户端依赖，如果你不使用 Zipkin 的话，麻烦把 ZIpkin 的相关包都依赖删除掉。即删除掉如下：

```xml
<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin</artifactId>
			<version>1.19.2</version>
		</dependency>

		<dependency>
			<groupId>io.zipkin.reporter</groupId>
			<artifactId>zipkin-reporter</artifactId>
			<version>0.6.12</version>
		</dependency>
```
