### ISSUE TITLE
DataSourceBeanFactoryPostProcessor抛出异常

### ISSUE THREAD

**Issue by rayzeng** [alipay/sofa-tracer#80]
### Describe the bug

升级sofa-boot 2.5.0后，启动失败
java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.beans.factory.config.TypedStringValue
	at com.alipay.sofa.tracer.boot.datasource.processor.DataSourceBeanFactoryPostProcessor.createDataSourceProxy(DataSourceBeanFactoryPostProcessor.java:123) ~[tracer-sofa-boot-starter-2.2.0.jar:2.2.0]
	at com.alipay.sofa.tracer.boot.datasource.processor.DataSourceBeanFactoryPostProcessor.postProcessBeanFactory(DataSourceBeanFactoryPostProcessor.java:63) ~[tracer-sofa-boot-starter-2.2.0.jar:2.2.0]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:178) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]

url = jdbc:mysql://1.1.1.1:3306/xxx?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

- SOFATracer version: 2.2.0
- JVM version (e.g. `java -version`):1.8

**Comment by khotyn** [comment]
@rayzeng 能把你的相关的 Bean 的配置贴一下吗？

**Comment by khotyn** [comment]
@QilongZhang 请帮忙跟进下这个 issue~

**Comment by QilongZhang** [comment]
> 是通过BeanDefinitionBuilder.addPropertyValue从配置中心读取配置初始化的，建议加个类型判断，是TypedStringValue还是String，以兼容这种场景

抱歉，手动构建BeanDefinition这种用法没有测试到。另外能否写一个简单的复现demo，我看下是否还有其他问题。

**Comment by QilongZhang** [comment]
@rayzeng   已在 [PR](https://github.com/alipay/sofa-tracer/pull/83) 修复。
